services:
  local_postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
      PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: "False"
      PGADMIN_CONFIG_WTF_CSRF_HEADERS: "['X-CSRF-Token', 'X-CSRFToken']"
      PGADMIN_CONFIG_WTF_CSRF_SSL_STRICT: "False"
      PGADMIN_CONFIG_WTF_CSRF_TIME_LIMIT: "3600"
      PGADMIN_CONFIG_WTF_CSRF_METHODS: "['POST', 'PUT', 'PATCH', 'DELETE']"
    ports:
      - "8080:80"
    depends_on:
      - local_postgres
    restart: unless-stopped

volumes:
  postgres-data:


  
