name: Build and Deploy Code
on: [push, pull_request]
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: pulling git repo
              uses: actions/checkout@v2
            - name: installing python version 3.12
              uses: actions/setup-python@v2
              with:
                python-version: '3.12'
            - name: updating pip
              run: python -m pip install --upgrade pip
            - name: installing all dependencies
              run: pip install -r requirements.txt
            
