name: Build and Deploy Code
on: [push, pull_request]
jobs:
    job1:
        env:
          DATABASE_HOSTNAME: localhost
          DATABASE_PORT: 5432
          DATABASE_PASSWORD: password
          DATABASE_NAME: fastapi
          DATABASE_USERNAME: postgres
          SECRET_KEY: ad0ec22a0b760e82e3572e49e098f65e0b1abf5da2e8ba8b269d34909a83099b
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
        runs-on: ubuntu-latest
        steps:
            - name: pulling git repo
              uses: actions/checkout@v2
            - name: installing python version 3.12
              uses: actions/setup-python@v2
              with:
                python-version: '3.12'
            - name: updating pip
              run: python -m pip install --upgrade pip
            - name: installing all dependencies
              run: pip install -r requirements.txt
            - name: testing with pytest
              run: |
                pip install pytest
                pytest
              
